# This starts up a simulator that tries to do what our Lambda@Edge does.

name: AWS Lambda@Edge

on:
  pull_request:
    branches:
      - main
    paths:
      - deployer/aws-lambda/**
      - libs/**
      - .github/workflows/aws-lambda.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Since we're using workspaces, we need to install in the root folder.

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cached-node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
        if: steps.cached-node_modules.outputs.cache-hit != 'true'

      - name: Run test server
        working-directory: deployer/aws-lambda/tests
        run: |
          npm run serve > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Check that the server started
        run: curl --retry-connrefused --retry 5 -I http://localhost:7000/ping

      - name: Preflight the integration tests
        run: |
          curl -I http://localhost:7000/docs/Web
          curl -I http://localhost:7000/en-US/docs/Web/

      - name: End-to-end test
        working-directory: deployer/aws-lambda/tests
        run: |
          npm run test-server

      - name: Debug any server outputs
        if: failure()
        run: |
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
